# Generated by Django 3.2.6 on 2021-08-17 03:02

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pembicara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama', models.CharField(max_length=100)),
                ('panggilan', models.CharField(blank=True, max_length=30)),
                ('Slug', models.SlugField(default='', editable=False, max_length=140)),
                ('Pekerjaan', models.CharField(max_length=100)),
                ('Perusahaan', models.CharField(max_length=100)),
                ('Deskripsi_singkat', models.TextField(blank=True)),
                ('Foto', models.ImageField(upload_to='web/')),
                ('Email', models.EmailField(blank=True, max_length=254)),
                ('Facebook', models.URLField(blank=True)),
                ('Twitter', models.URLField(blank=True)),
                ('Linkedin', models.URLField(blank=True)),
                ('Instagram', models.URLField(blank=True)),
                ('Keterangan', models.TextField(blank=True)),
                ('keynote', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Pembicara',
                'verbose_name_plural': 'Pembicara',
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='web/logosponsor')),
                ('kategori', models.CharField(choices=[('0', 'University Sponsors'), ('1', 'Corporate Sponsors'), ('2', 'Media Sponsors')], default=0, max_length=1)),
                ('keterangan', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('panggilan', models.CharField(blank=True, max_length=30)),
                ('jabatan', models.CharField(blank=True, max_length=150)),
                ('foto', models.ImageField(blank=True, upload_to='web/teams/')),
                ('keterangan', models.TextField(blank=True)),
                ('no_urut', models.PositiveIntegerField(blank=True)),
                ('scientific_coord', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'team',
                'verbose_name_plural': 'teams',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Judul', models.CharField(max_length=100)),
                ('Slug', models.SlugField(default='', editable=False, max_length=140)),
                ('Mulai', models.DateTimeField()),
                ('Selesai', models.DateTimeField(blank=True)),
                ('Lokasi', models.TextField(blank=True)),
                ('Link', models.URLField(blank=True)),
                ('Keterangan', models.TextField(blank=True)),
                ('Pembicara', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='web.pembicara')),
            ],
            options={
                'verbose_name': 'Acara',
                'verbose_name_plural': 'Acara',
            },
        ),
        migrations.CreateModel(
            name='Artikel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Judul', models.CharField(max_length=150)),
                ('Slug', models.SlugField(default='', editable=False, max_length=140)),
                ('Tanggal', models.DateField(null=True)),
                ('Isi', tinymce.models.HTMLField()),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Artikel',
                'verbose_name_plural': 'Artikel',
            },
        ),
    ]
